# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-12 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costumuser',
            name='role',
            field=models.CharField(max_length=30),
        ),
    ]
