# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 13:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0001_initial'),
        ('registration', '0002_auto_20170312_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='costumuser',
            name='subjects',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userSubjects', to='subject.Subject'),
        ),
    ]
