# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 12:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_costumuser_subjects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='costumuser',
            name='subjects',
        ),
    ]
