# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0002_subject_teacher'),
        ('registration', '0004_remove_costumuser_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='costumuser',
            name='attendingSubject',
            field=models.ManyToManyField(to='subject.Subject'),
        ),
    ]
