# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 18:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_costumuser_attendingsubject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='costumuser',
            name='attendingSubject',
        ),
    ]
