# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0003_auto_20170320_1857'),
        ('registration', '0006_remove_costumuser_attendingsubject'),
    ]

    operations = [
        migrations.AddField(
            model_name='costumuser',
            name='attendingSubject',
            field=models.ManyToManyField(to='subject.Subject'),
        ),
    ]
