# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_costumuser_attendingsubject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costumuser',
            name='attendingSubject',
            field=models.ManyToManyField(related_name='attend_subject', to='subject.Subject'),
        ),
    ]
