# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-26 15:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
        ('subject', '0003_remove_subject_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjectTeacher', to='registration.CustomUser'),
        ),
    ]
