# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0002_auto_20170308_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectives',
            name='learning_objective',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
