# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 12:06
from __future__ import unicode_literals

import django.core.validators
import django.db.models.deletion
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subject', '0002_subject_teacher'),
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('term', models.CharField(max_length=10, verbose_name='Semester')),
                ('year', models.IntegerField(default=2017)),
                ('due', models.DateField(blank=True, default='datetime.datetime.now()')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Assignment', to='subject.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='MultipleChoiseQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('choises', multiselectfield.db.fields.MultiSelectField(choices=[('item_key1', 'Choice 0'), ('item_key2', 'Choice 1'), ('item_key3', 'Choice 2'), ('item_key4', 'Choice 3')], max_length=39)),
                ('answear', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)])),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MultipleChoiseQuestions', to='assignment.Assignment')),
            ],
        ),
        migrations.CreateModel(
            name='OneWordQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('answear', models.CharField(max_length=100)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='OneWordQuestions', to='assignment.Assignment')),
            ],
        ),
        migrations.CreateModel(
            name='TrueFalseQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('answear', models.BooleanField(default=False)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TrueFalseQuestions', to='assignment.Assignment')),
            ],
        ),
        migrations.CreateModel(
            name='UserAnswers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempts', models.IntegerField(default=0)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserAnswers', to='assignment.Assignment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.CostumUser')),
                ('wrongMCQ', models.ManyToManyField(to='assignment.MultipleChoiseQuestion')),
                ('wrongOWQ', models.ManyToManyField(to='assignment.OneWordQuestion')),
                ('wrongTFQ', models.ManyToManyField(to='assignment.TrueFalseQuestion')),
            ],
        ),
    ]
