# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 13:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('term', models.CharField(max_length=10, verbose_name='Semester')),
                ('year', models.IntegerField(default=2017)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Assignment', to='subject.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='MultipleChoiseQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('choises', multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Item title 1.1'), (2, 'Item title 1.2'), (3, 'Item title 1.3'), (4, 'Item title 1.4')], max_length=4)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MultipleChoiseQuestions', to='assignment.Assignment')),
            ],
        ),
        migrations.CreateModel(
            name='OneWordQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('answear', models.CharField(max_length=200)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='OneWordQuestions', to='assignment.Assignment')),
            ],
        ),
        migrations.CreateModel(
            name='TrueFalse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learning_objective', models.CharField(max_length=200)),
                ('answear', models.BooleanField()),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TrueFalseQuestions', to='assignment.Assignment')),
            ],
        ),
    ]
