# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 13:57
from __future__ import unicode_literals

import django.db.models.deletion
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrueFalseQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learning_objective', models.CharField(max_length=200)),
                ('answear', models.BooleanField(default=False)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TrueFalseQuestions', to='assignment.Assignment')),
            ],
        ),
        migrations.RemoveField(
            model_name='truefalse',
            name='assignment',
        ),
        migrations.AddField(
            model_name='multiplechoisequestion',
            name='answear',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='multiplechoisequestion',
            name='choises',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], max_length=7),
        ),
        migrations.DeleteModel(
            name='TrueFalse',
        ),
    ]
