# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 09:28
from __future__ import unicode_literals

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0003_auto_20170301_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multiplechoisequestion',
            name='choises',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('item_key1', 'Item title 1.1'), ('item_key2', 'Item title 1.2'), ('item_key3', 'Item title 1.3'), ('item_key4', 'Item title 1.4'), ('item_key5', 'Item title 1.5')], max_length=49),
        ),
    ]
