# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-12 15:16
from __future__ import unicode_literals

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0004_auto_20170302_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multiplechoisequestion',
            name='choises',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('item_key1', 'Choice 1'), ('item_key2', 'Choice 2'), ('item_key3', 'Choice 3'), ('item_key4', 'Choice 4')], max_length=39),
        ),
        migrations.AlterField(
            model_name='onewordquestion',
            name='answear',
            field=models.CharField(max_length=100),
        ),
    ]
