# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-17 10:45
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_remove_costumuser_subjects'),
        ('assignment', '0005_auto_20170312_1516'),
    ]

    operations = [
        migrations.CreateModel(
            name='userAnswers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempts', models.IntegerField(default=0)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment.Assignment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.CostumUser')),
                ('wrongMCQ', models.ManyToManyField(to='assignment.MultipleChoiseQuestion')),
                ('wrongOWQ', models.ManyToManyField(to='assignment.OneWordQuestion')),
                ('wrongTFQ', models.ManyToManyField(to='assignment.TrueFalseQuestion')),
            ],
        ),
    ]
