# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-17 12:20
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0006_useranswers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multiplechoisequestion',
            name='answear',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)]),
        ),
        migrations.AlterField(
            model_name='multiplechoisequestion',
            name='choises',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('item_key1', 'Choice 0'), ('item_key2', 'Choice 1'), ('item_key3', 'Choice 2'), ('item_key4', 'Choice 3')], max_length=39),
        ),
    ]
