# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-19 14:41
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0007_auto_20170317_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswers',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserAnswers', to='assignment.Assignment'),
        ),
    ]
