# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 12:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0009_assignment_due'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='tries',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='due',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 3, 20, 12, 4, 6, 565426)),
        ),
    ]
