# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 18:57
from __future__ import unicode_literals

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0012_auto_20170320_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='due',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 3, 20, 18, 57, 16, 150353)),
        ),
    ]
